#!/bin/sh
 
usage()
{	
	echo "**************build stream from RTMPLive demo******************"
	echo "1. build 32bit program ./Buildit i386 [target in i386]"	
	echo "2. build 64bit program ./Buildit x64 [target in x64]"	
	echo "3. clean up ./Buildit clean"
	echo "-----------------------------------------------------------"
}


if [ "$*" = "clean" ] ; then
	cd RTMPLive
	make -f nbproject/Makefile-i386.mk QMAKE= SUBPROJECTS= .clean-conf		
	make -f nbproject/Makefile-x64.mk QMAKE= SUBPROJECTS= .clean-conf
elif [ "$*" = "x64" ] ; then
    cd RTMPLive
    make -f nbproject/Makefile-x64.mk QMAKE= SUBPROJECTS= .build-conf
elif [ "$*" = "i386" ] ; then
    cd RTMPLive
    make -f nbproject/Makefile-i386.mk QMAKE= SUBPROJECTS= .build-conf
else
	usage;
fi
