#!/bin/sh
 
usage()
{	
	echo "**************build stream from EasyRTSPLive demo******************"
	echo "1. build 32bit program ./Buildit x86 [target in x86]"	
	echo "2. build 64bit program ./Buildit x64 [target in x64]"	
	echo "3. clean up ./Buildit clean"
	echo "-----------------------------------------------------------"
}


if [ "$*" = "clean" ] ; then
	cd EasyRTSPLive
	make -f nbproject/Makefile-x86.mk QMAKE= SUBPROJECTS= .clean-conf		
	make -f nbproject/Makefile-x64.mk QMAKE= SUBPROJECTS= .clean-conf
elif [ "$*" = "x64" ] ; then
    cd EasyRTSPLive
    make -f nbproject/Makefile-x64.mk QMAKE= SUBPROJECTS= .build-conf
elif [ "$*" = "x86" ] ; then
    cd EasyRTSPLive
    make -f nbproject/Makefile-x86.mk QMAKE= SUBPROJECTS= .build-conf
else
	usage;
fi
